# Generated by Django 4.0.10 on 2024-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
