# Generated by Django 4.0.10 on 2024-01-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='site_name',
            field=models.CharField(default='pracuj.pl', max_length=50),
            preserve_default=False,
        ),
    ]
